name: FakeLags
version: '${version}'
main: hw.zako.fakelags.FakeLags
api-version: '1.16'
commands:
  cheaterenablelags:
    permission: trolling.admin
    usage: /cheaterenablelags [player]
depend:
  - packetevents